/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/knative/eventing-contrib/contrib/alimns/pkg/apis/sources/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAliMnsSources implements AliMnsSourceInterface
type FakeAliMnsSources struct {
	Fake *FakeSourcesV1alpha1
	ns   string
}

var alimnssourcesResource = schema.GroupVersionResource{Group: "sources.knative.dev", Version: "v1alpha1", Resource: "alimnssources"}

var alimnssourcesKind = schema.GroupVersionKind{Group: "sources.knative.dev", Version: "v1alpha1", Kind: "AliMnsSource"}

// Get takes name of the mnsSource, and returns the corresponding mnsSource object, and an error if there is any.
func (c *FakeAliMnsSources) Get(name string, options v1.GetOptions) (result *v1alpha1.AliMnsSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(alimnssourcesResource, c.ns, name), &v1alpha1.AliMnsSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AliMnsSource), err
}

// List takes label and field selectors, and returns the list of AliMnsSources that match those selectors.
func (c *FakeAliMnsSources) List(opts v1.ListOptions) (result *v1alpha1.AliMnsSourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(alimnssourcesResource, alimnssourcesKind, c.ns, opts), &v1alpha1.AliMnsSourceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AliMnsSourceList{ListMeta: obj.(*v1alpha1.AliMnsSourceList).ListMeta}
	for _, item := range obj.(*v1alpha1.AliMnsSourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested mnsSources.
func (c *FakeAliMnsSources) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(alimnssourcesResource, c.ns, opts))

}

// Create takes the representation of a mnsSource and creates it.  Returns the server's representation of the mnsSource, and an error, if there is any.
func (c *FakeAliMnsSources) Create(mnsSource *v1alpha1.AliMnsSource) (result *v1alpha1.AliMnsSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(alimnssourcesResource, c.ns, mnsSource), &v1alpha1.AliMnsSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AliMnsSource), err
}

// Update takes the representation of a mnsSource and updates it. Returns the server's representation of the mnsSource, and an error, if there is any.
func (c *FakeAliMnsSources) Update(mnsSource *v1alpha1.AliMnsSource) (result *v1alpha1.AliMnsSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(alimnssourcesResource, c.ns, mnsSource), &v1alpha1.AliMnsSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AliMnsSource), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAliMnsSources) UpdateStatus(mnsSource *v1alpha1.AliMnsSource) (*v1alpha1.AliMnsSource, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(alimnssourcesResource, "status", c.ns, mnsSource), &v1alpha1.AliMnsSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AliMnsSource), err
}

// Delete takes name of the mnsSource and deletes it. Returns an error if one occurs.
func (c *FakeAliMnsSources) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(alimnssourcesResource, c.ns, name), &v1alpha1.AliMnsSource{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAliMnsSources) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(alimnssourcesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.AliMnsSourceList{})
	return err
}

// Patch applies the patch and returns the patched mnsource.
func (c *FakeAliMnsSources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AliMnsSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(alimnssourcesResource, c.ns, name, pt, data, subresources...), &v1alpha1.AliMnsSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AliMnsSource), err
}
