/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/knative/eventing-contrib/contrib/alimns/pkg/apis/sources/v1alpha1"
	scheme "github.com/knative/eventing-contrib/contrib/alimns/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AliMnsSourcesGetter has a method to return a AliMnsSourceInterface.
// A group's client should implement this interface.
type AliMnsSourcesGetter interface {
	AliMnsSources(namespace string) AliMnsSourceInterface
}

// AliMnsSourceInterface has methods to work with AliMnsSource resources.
type AliMnsSourceInterface interface {
	Create(*v1alpha1.AliMnsSource) (*v1alpha1.AliMnsSource, error)
	Update(*v1alpha1.AliMnsSource) (*v1alpha1.AliMnsSource, error)
	UpdateStatus(*v1alpha1.AliMnsSource) (*v1alpha1.AliMnsSource, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.AliMnsSource, error)
	List(opts v1.ListOptions) (*v1alpha1.AliMnsSourceList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AliMnsSource, err error)
	AliMnsSourceExpansion
}

// mnsSources implements AliMnsSourceInterface
type alimnsSources struct {
	client rest.Interface
	ns     string
}

// newAliMnsSources returns a AliMnsSources
func newAliMnsSources(c *SourcesV1alpha1Client, namespace string) *alimnsSources {
	return &alimnsSources{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the mnsSource, and returns the corresponding mnsSource object, and an error if there is any.
func (c *alimnsSources) Get(name string, options v1.GetOptions) (result *v1alpha1.AliMnsSource, err error) {
	result = &v1alpha1.AliMnsSource{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("alimnssources").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AliMnsSources that match those selectors.
func (c *alimnsSources) List(opts v1.ListOptions) (result *v1alpha1.AliMnsSourceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.AliMnsSourceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("alimnssources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch alimnsSources a watch.Interface that watches the requested mnsSources.
func (c *alimnsSources) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("alimnssources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a mnsSource and creates it.  Returns the server's representation of the mnsSource, and an error, if there is any.
func (c *alimnsSources) Create(mnsSource *v1alpha1.AliMnsSource) (result *v1alpha1.AliMnsSource, err error) {
	result = &v1alpha1.AliMnsSource{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("alimnssources").
		Body(mnsSource).
		Do().
		Into(result)
	return
}

// Update takes the representation of a mnsSource and updates it. Returns the server's representation of the mnsSource, and an error, if there is any.
func (c *alimnsSources) Update(mnsSource *v1alpha1.AliMnsSource) (result *v1alpha1.AliMnsSource, err error) {
	result = &v1alpha1.AliMnsSource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("alimnssources").
		Name(mnsSource.Name).
		Body(mnsSource).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *alimnsSources) UpdateStatus(mnsSource *v1alpha1.AliMnsSource) (result *v1alpha1.AliMnsSource, err error) {
	result = &v1alpha1.AliMnsSource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("alimnssources").
		Name(mnsSource.Name).
		SubResource("status").
		Body(mnsSource).
		Do().
		Into(result)
	return
}

// Delete takes name of the alimnsSources and deletes it. Returns an error if one occurs.
func (c *alimnsSources) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("alimnssources").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *alimnsSources) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("alimnssources").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched alimnsSources.
func (c *alimnsSources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AliMnsSource, err error) {
	result = &v1alpha1.AliMnsSource{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("alimnssources").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
